# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
from openerp import api, fields, models

## Comentado el modelo usado anteriormente,
## ahora se usa res.country.state
## el cual está dentro de "base"
#class Estado(models.Model):
#    """Estados de Venezuela"""
#    _name = 'estado'
#    _rec_name = 'estado'
#    codigo = fields.Char('Código', size=3, required=True, help='Código del Estado')
#    estado = fields.Char('Estado',size=30,required=True, help='Nombre del Estado')


class Municipio(models.Model):
    """Municipios de los Estados de Venezuela"""
    _name = 'municipio'
    _rec_name = 'nombre'
    codigo = fields.Char('Código',size=3,required=True, help='Código del Municipio')
    nombre = fields.Char('Municipio',size=30,required=True, help='Código del Municipio')
    res_country_state_id = fields.Many2one('res.country.state','Estado', help='Nombre del Estado al cual pertenece el municipio')


class Parroquia(models.Model):
    """Parroquia de los Estados de Venezuela"""
    _name = 'parroquia'
    _rec_name = 'nombre'
    codigo = fields.Char('Código',size=3,required=True, help='Código de Identificación de la Parroquia')
    nombre = fields.Char('Parroquia',size=30,required=True, help='Nombre de la Parroquia')
    municipio_id = fields.Many2one('municipio', 'Municipio', help='Municipio al cual pertenece la Parroquia')
